name: Homebrew

on:
  workflow_run:
    workflows:
      - "Release"
    types:
      - completed

jobs:
  brew:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          # Required, custom GitHub access token with the 'public_repo' and 'workflow' scopes
          token: ${{secrets.BREW_TOKEN}}
          # Formula name, required
          formula: forgit
