name: Tag

on:
  schedule:
    # Run on every first day of the month
    - cron: '0 0 1 * *'

jobs:

  tag:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # The COMMIT_KEY secret contains a private SSH key. The associated public key
          # has been added as a deploy key in the GitHub project. See:
          # https://docs.github.com/en/developers/overview/managing-deploy-keys#deploy-keys
          # This is necessary to make commits done by github-actions able to trigger
          # further github-actions. See: https://stackoverflow.com/q/60418323/3018229.
          ssh-key: "${{secrets.COMMIT_KEY}}"

      - name: Create Tag
        run: .github/scripts/tag.sh
        env:
          REPO_URL: ${{github.server_url}}/${{github.repository}}
